# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

add_files C:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/design_gpio_interrupt.bd
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_processing_system7_0_0/design_gpio_interrupt_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_axi_gpio_0_0/design_gpio_interrupt_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_axi_gpio_0_0/design_gpio_interrupt_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_axi_gpio_0_0/design_gpio_interrupt_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_axi_gpio_1_0/design_gpio_interrupt_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_axi_gpio_1_0/design_gpio_interrupt_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_axi_gpio_1_0/design_gpio_interrupt_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_processing_system7_0_50M_0/design_gpio_interrupt_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_processing_system7_0_50M_0/design_gpio_interrupt_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_processing_system7_0_50M_0/design_gpio_interrupt_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_xbar_0/design_gpio_interrupt_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_auto_pc_0/design_gpio_interrupt_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/design_gpio_interrupt_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/design_gpio_interrupt.bd]

read_verilog -library xil_defaultlib C:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.srcs/sources_1/bd/design_gpio_interrupt/hdl/design_gpio_interrupt_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/VRL/GPIO_Interrupt/GPIO_Interrupt.cache/wt [current_project]
set_property parent.project_dir C:/Users/VRL/GPIO_Interrupt [current_project]
catch { write_hwdef -file design_gpio_interrupt_wrapper.hwdef }
synth_design -top design_gpio_interrupt_wrapper -part xc7z020clg484-1
write_checkpoint design_gpio_interrupt_wrapper.dcp
report_utilization -file design_gpio_interrupt_wrapper_utilization_synth.rpt -pb design_gpio_interrupt_wrapper_utilization_synth.pb
